/* ══════════════════════════════════════════════════════════════════════════
   LOBO ADAPTATION — the adversary evolves from what actually beat it.

   Ghost, 2026-08-24: "everything is the subject of the test. this isnt about
   any single feature, its about evolving our own genome by means unrelated to
   us... therefore we should have less of our own blindspots to detect and more
   from something else. decreasing the need for outside viewers this early."

   THIS IS WHY THE LADDER IS NOT AUTHORED. An adversary that unlocks a fixed
   list in a fixed order is still OUR imagination, just on a delay: the colony
   can only ever evolve answers to pressures we thought of, so our blindspots
   propagate into it invisibly and nothing in the run can reveal them.

   So the trigger is the RUN'S OWN HISTORY. LOBO records why each wave died and
   adopts the counter to whatever is killing it most. The colony's successful
   defence is what creates the next threat — selection pressure generated by the
   interaction rather than by either of us. That is the sense in which this
   evolves "by means unrelated to us", and it is the same loop as the colony's
   own honorable-death inheritance, pointed the other way.

   WHAT IT DOES NOT TOUCH: the scripted war games. Those stay a controlled
   instrument, because comparison has to live somewhere — a range needs one
   surface that is identical every run and one that is genuinely open. Free runs
   are where discovery happens; the exercises are where measurement happens.
   ══════════════════════════════════════════════════════════════════════════ */

window.MurmurationModules = window.MurmurationModules || {};

window.MurmurationModules.LoboEvolve = class LoboEvolve {
  constructor(world, opts = {}) {
    this.world = world;
    this.enabled = opts.enabled !== false;

    // Causes of death LOBO can actually distinguish. Each maps to one counter.
    // Nothing here is a guess about what the colony WILL do — these are only
    // read after the colony has already done it.
    this.CAUSES = {
      COORDINATED: 'defenders converged from beyond line of sight',
      WALLED:      'died in the keep without reaching the crown',
      QUORUM:      'repelled by a massed, confirmed response',
      STARVED:     'expired in the field without reaching anything',
      GUARDED:     'stopped by the crown detail'
    };

    // The counters. Adopted only when the matching cause dominates.
    this.TRAITS = {
      INFILTRATION: { counter: 'COORDINATED', adopted: false,
        trait: 'Infiltration (Cuckoo)',
        desc: 'move as few, avoid contact — an alarm nobody triggers is never raised' },
      SAPPER:       { counter: 'WALLED', adopted: false,
        trait: 'Sapper (Termite)',
        desc: 'patience at the wall: hold the gap line instead of battering the ring' },
      FEINT:        { counter: 'QUORUM', adopted: false,
        trait: 'Feint (Anglerfish)',
        desc: 'split into probes too small to confirm — stay under the quorum' },
      FORAGE:       { counter: 'STARVED', adopted: false,
        trait: 'Forage (Locust)',
        desc: 'sustain in the field; a siege no longer runs out before the colony does' },
      DECOY:        { counter: 'GUARDED', adopted: false,
        trait: 'Decoy (Plover)',
        desc: 'draw the detail off the crown before committing' }
    };

    this.deaths = {};                 // cause -> count, this cycle
    this.total = 0;
    this.history = [];                // every adoption, with the evidence
    this.THRESHOLD = opts.threshold ?? 12;   // deaths before it may adapt
  }

  /** Record why one attacker died. Called by whoever kills it. */
  recordDeath(cause) {
    if (!this.enabled || !this.CAUSES[cause]) return;
    this.deaths[cause] = (this.deaths[cause] || 0) + 1;
    this.total++;
  }

  /**
   * Classify a death from the state around it. Deliberately conservative: an
   * unattributable death is counted as nothing rather than guessed at, because
   * a miscounted cause would teach LOBO the wrong lesson and there is no outside
   * reviewer here to catch it.
   */
  classify(agent, ctx) {
    if (!agent) return null;
    const keep = ctx && ctx.keep, alarm = ctx && ctx.alarm;
    if (keep && ctx.insideKeep) return 'WALLED';
    if (ctx && ctx.guardsNear >= 2) return 'GUARDED';
    // Converged-from-away only counts when the colony COULD have been called:
    // without the alarm unlocked there is nothing to converge on.
    if (alarm && alarm.enabled && ctx && ctx.defendersNear >= 4) return 'COORDINATED';
    if (ctx && ctx.defendersNear >= 6) return 'QUORUM';
    if (ctx && ctx.starved) return 'STARVED';
    return null;
  }

  /** Adopt the counter to whatever is killing LOBO most. Returns it, or null. */
  adapt() {
    if (!this.enabled || this.total < this.THRESHOLD) return null;
    let cause = null, n = 0;
    for (const c in this.deaths) if (this.deaths[c] > n) { n = this.deaths[c]; cause = c; }
    if (!cause) return null;
    const key = Object.keys(this.TRAITS).find(k =>
      this.TRAITS[k].counter === cause && !this.TRAITS[k].adopted);
    // Reset the tally either way: a cause whose counter LOBO already carries
    // must not keep blocking adaptation to the next thing killing it.
    const evidence = { cause, n, of: this.total, at: this.world.time };
    this.deaths = {}; this.total = 0;
    if (!key) return null;
    this.TRAITS[key].adopted = true;
    this.history.push({ key, ...evidence });
    return { key, ...this.TRAITS[key], evidence };
  }

  has(key) { return !!(this.TRAITS[key] && this.TRAITS[key].adopted); }
  adoptedList() { return Object.keys(this.TRAITS).filter(k => this.TRAITS[k].adopted); }

  stats() {
    return {
      enabled: this.enabled,
      towardNext: this.total + '/' + this.THRESHOLD,
      leadingCause: (() => {
        let c = null, n = 0;
        for (const k in this.deaths) if (this.deaths[k] > n) { n = this.deaths[k]; c = k; }
        return c ? c + ' ×' + n : '—';
      })(),
      adopted: this.adoptedList()
    };
  }
};
