/* ══════════════════════════════════════════════════════════════════════════
   LOBO ADAPTATION — the adversary evolves from what actually beat it.

   Ghost, 2026-08-24: "everything is the subject of the test. this isnt about
   any single feature, its about evolving our own genome by means unrelated to
   us... therefore we should have less of our own blindspots to detect and more
   from something else. decreasing the need for outside viewers this early."

   THIS IS WHY THE LADDER IS NOT AUTHORED. An adversary that unlocks a fixed
   list in a fixed order is still OUR imagination, just on a delay: the colony
   can only ever evolve answers to pressures we thought of, so our blindspots
   propagate into it invisibly and nothing in the run can reveal them.

   So the trigger is the RUN'S OWN HISTORY. LOBO records why each wave died and
   adopts the counter to whatever is killing it most. The colony's successful
   defence is what creates the next threat — selection pressure generated by the
   interaction rather than by either of us. That is the sense in which this
   evolves "by means unrelated to us", and it is the same loop as the colony's
   own honorable-death inheritance, pointed the other way.

   WHAT IT DOES NOT TOUCH: the scripted war games. Those stay a controlled
   instrument, because comparison has to live somewhere — a range needs one
   surface that is identical every run and one that is genuinely open. Free runs
   are where discovery happens; the exercises are where measurement happens.
   ══════════════════════════════════════════════════════════════════════════ */

window.MurmurationModules = window.MurmurationModules || {};

window.MurmurationModules.LoboEvolve = class LoboEvolve {
  constructor(world, opts = {}) {
    this.world = world;
    this.enabled = opts.enabled !== false;

    // Causes of death LOBO can actually distinguish. Each maps to one counter.
    // Nothing here is a guess about what the colony WILL do — these are only
    // read after the colony has already done it.
    this.CAUSES = {
      COORDINATED: 'defenders converged from beyond line of sight',
      WALLED:      'died in the keep without reaching the crown',
      QUORUM:      'repelled by a massed, confirmed response',
      STARVED:     'expired in the field without reaching anything',
      GUARDED:     'stopped by the crown detail'
    };

    // The counters. Adopted only when the matching cause dominates.
    this.TRAITS = {
      INFILTRATION: { counter: 'COORDINATED', adopted: false,
        trait: 'Infiltration (Cuckoo)',
        desc: 'move as few, avoid contact — an alarm nobody triggers is never raised' },
      SAPPER:       { counter: 'WALLED', adopted: false,
        trait: 'Sapper (Termite)',
        desc: 'patience at the wall: hold the gap line instead of battering the ring' },
      FEINT:        { counter: 'QUORUM', adopted: false,
        trait: 'Feint (Anglerfish)',
        desc: 'split into probes too small to confirm — stay under the quorum' },
      FORAGE:       { counter: 'STARVED', adopted: false,
        trait: 'Forage (Locust)',
        desc: 'sustain in the field; a siege no longer runs out before the colony does' },
      DECOY:        { counter: 'GUARDED', adopted: false,
        trait: 'Decoy (Plover)',
        desc: 'draw the detail off the crown before committing' }
    };

    this.deaths = {};                 // cause -> count, this cycle
    this.total = 0;
    this.history = [];                // every adoption, with the evidence
    this.THRESHOLD = opts.threshold ?? 12;   // deaths before it may adapt
    this.initConquest(opts);                 // finite muster + the conquest tiers
    // Carry forward what earlier campaigns taught it. A fresh campaign,
    // an experienced adversary.
    this.carriedIn = (opts.forget ? (this.forgetLearning(), []) : this.restoreLearning());
  }

  /* ── CONQUEST — LOBO's honor, and deliberately NOT the colony's ──────────
     Ghost, 2026-08-24: "its system has to be inherently different because if
     not we'd be right back here running the devil gene next."

     That is a constitutional argument, not an aesthetic one. Symmetric value
     systems converge: give LOBO an honor that bleeds, heals and governs its
     exits and it becomes a second colony wearing a different flag — at which
     point it needs the same oversight, and the Devil Gene has to be pointed at
     the adversary too. So the shapes are opposite on purpose.

       COLONY honor  earned by what you GIVE UP — seppuku, the crown defended,
                     effort brought to the clan. Continuous 0..1. It BLEEDS when
                     the crown is taken and HEALS when it is safe. It is a
                     STATE, and states can be wrong, which is why the colony
                     needs a skeptic.
       LOBO honor    earned by what you TAKE. Discrete tiers, never bled, never
                     healed, never recovered. It is a RECORD of what happened,
                     and a record has nothing to be skeptical of.

     ON THE MUSTER — SUPERSEDED, and the history is kept because the reasoning
     changed rather than being wrong. It was capped so a run could be lost by
     attrition; it is uncapped now because attrition was the wrong axis. See
     initConquest() below and SOVEREIGN_RULINGS SR-010. One consequence must be
     tracked rather than assumed: the honored break-off was made load-bearing BY
     the cap, since withdrawal is meaningless while bodies are free. Uncapped, it
     survives only because LOBO's honor counts what its dead BOUGHT, so spending
     without gain still costs it something. */
  /* ── WHAT IT LEARNED PERSISTS; WHAT IT TOOK DOES NOT ────────────────────
     Ghost, 2026-08-25, after the first full campaign: LOBO taught itself two
     counters from its own failures, then the muster ran out before it could
     reach the one that would actually beat a crown. The muster was shorter than
     the learning curve — it kept dying to the WALL, so it kept learning wall
     lessons, and never accumulated the GUARDED evidence that yields DECOY.

     Handing it more bodies would have papered over that. Instead the ADAPTATION
     carries between campaigns while the campaign itself starts clean. The split
     is the same one that governs its honor: what LOBO LEARNED is knowledge and
     survives; what it TOOK is a campaign record and resets, or no run could be
     won or lost again.

     Consequence worth stating plainly: the range gets harder every time it is
     run. A colony that beat LOBO yesterday faces a smarter LOBO today, and the
     defence has to keep earning it. That is the point. */
  _memKey() { return 'attrition.lobo.learned.v1'; }

  saveLearning() {
    try {
      const adopted = this.adoptedList();
      window.localStorage.setItem(this._memKey(), JSON.stringify({
        adopted, history: this.history.slice(-20), savedAt: Date.now()
      }));
      return adopted;
    } catch (e) { return null; }   // private mode / no storage — learning is just per-session
  }

  restoreLearning() {
    try {
      const raw = window.localStorage.getItem(this._memKey());
      if (!raw) return [];
      const d = JSON.parse(raw);
      for (const k of (d.adopted || [])) if (this.TRAITS[k]) this.TRAITS[k].adopted = true;
      this.history = d.history || [];
      return d.adopted || [];
    } catch (e) { return []; }
  }

  /** Wipe what LOBO knows — the only way back to a true naive baseline. */
  forgetLearning() {
    try { window.localStorage.removeItem(this._memKey()); } catch (e) {}
    for (const k in this.TRAITS) this.TRAITS[k].adopted = false;
    this.history = [];
    return true;
  }

  initConquest(opts = {}) {
    /* NO CAP (Ghost, 2026-08-25 — superseding the finite muster of hours
       earlier). "with this slider lobo doesnt need a cap which is a far more
       productive path and the original one and structurally correct."

       He is right and it is worth writing down why. A muster made the run
       decidable by ATTRITION: whoever ran out first lost. But a real adversary
       does not run out — what is finite in the world being modelled is the
       DEFENDER'S attention, and that is now modelled directly by stress. With
       paranoia and fatigue moving the threshold a colony decides at, and
       Population Boom letting it replenish to its own ceiling, the question
       stops being "can LOBO outlast them" and becomes "can they keep deciding
       well under pressure that never stops." That is the blue-team question.

       null = unlimited. draw() passes everything through, exhausted() is never
       true, and a run is decided by CROWNED or by nothing — which is correct,
       because a defence that merely survives an attacker's supply has not been
       shown to be good, only to have been lucky about how much was sent. */
    this.muster = opts.muster ?? null;   // null = no cap
    this.spent = 0;
    this.kingsTaken = 0;
    this.silentKills = 0;                // kings taken with the alarm never raised
    this.tier = null;
    this.tiersEarned = [];
    return this;
  }

  TIERS() {
    return [
      { id:'BLOODED', at:'kingsTaken>=1', name:'Blooded',
        desc:'a crown has fallen to it' },
      { id:'ELITE',   at:'kingsTaken>=2', name:'Elite',
        desc:'both crowns taken — nothing on the map went unbeaten' },
      { id:'CROWNED', at:'kingsTaken>=3', name:'Crowned',
        desc:'more than two: the colonies re-crowned and it took those too, so it holds a crown of its own' },
      // The ultimate prize is defined AGAINST trait #51. It cannot be won by
      // force at all — only by never being heard.
      { id:'PHANTOM', at:'silentKills>=1', name:'Phantom',
        desc:'a crown taken without the alarm ever being raised — a stealth takeover' }
    ];
  }

  /** Draw from the muster. Returns how many LOBO can actually field. */
  draw(n) {
    if (this.muster == null) return n;             // conquest not armed
    const got = Math.max(0, Math.min(n, this.muster - this.spent));
    this.spent += got;
    return got;
  }
  remaining() { return this.muster == null ? Infinity : Math.max(0, this.muster - this.spent); }
  exhausted() { return this.remaining() <= 0; }

  /**
   * A crown has fallen. `silent` is true only if the alarm was never raised for
   * that colony during the attempt — the caller owns that judgement, because
   * only it can see the field.
   */
  recordKingTaken(silent) {
    // NOT gated on the muster. Uncapping LOBO must never remove its ability to
    // WIN — the same bug lived here and in verdict(), and either one alone made
    // an uncapped campaign unwinnable while looking fine.
    this.kingsTaken++;
    if (silent) this.silentKills++;
    const won = [];
    for (const t of this.TIERS()) {
      if (this.tiersEarned.includes(t.id)) continue;
      const ok = t.id === 'PHANTOM' ? this.silentKills >= 1
               : t.id === 'CROWNED' ? this.kingsTaken >= 3
               : t.id === 'ELITE'   ? this.kingsTaken >= 2
               : this.kingsTaken >= 1;
      if (ok) { this.tiersEarned.push(t.id); this.tier = t.id; won.push(t); }
    }
    return won.length ? won : null;
  }

  /* ── H2O — THE STEALTH GATE ─────────────────────────────────────────────
     Ghost, 2026-08-25: "we need to figure out how to have lobo incorporate h2o
     possibly for those stealth hits."

     H2O is the pentest engine's constitutional constraint — "never knowingly
     decrease correspondence" — and its defining property is that it is
     STRUCTURAL: "It runs before the action, not after. The engine physically
     cannot generate a low-confidence finding." It does not punish a bad call, it
     makes the bad call unavailable.

     That is the right shape for stealth, because a FAILED silent approach is
     strictly worse than an honest assault: it spends the same bodies, loses
     surprise, AND raises the alarm that INFILTRATION exists to avoid. Committing
     to silence you cannot keep is exactly "knowingly decreasing correspondence"
     — claiming a capability the situation does not support.

     So the gate runs before the commitment, and refuses rather than gambles.
     It also protects the PHANTOM tier from being won by luck (SR-009 forecloses
     awarding it on a judgement call): a stealth kill now has to be a stealth
     ATTEMPT that was earned before it began. */
  H2O_FLOOR = 0.55;

  h2oStealthGate(ctx = {}) {
    const reasons = [];
    let c = 1.0;

    // You cannot move unheard without having learned how. INFILTRATION is the
    // counter to coordinated defence and the only trait that avoids contact.
    if (!this.has('INFILTRATION')) {
      return { allowed:false, confidence:0, reason:'no capability for silence — INFILTRATION not adopted' };
    }
    // If the colony is ALREADY roused, there is no silence left to keep. This is
    // correspondence in its plainest form: the claim "they will not hear us" is
    // already false.
    if (ctx.alarmLevel > 0.05) {
      return { allowed:false, confidence:0, reason:'the colony is already roused — the silence is spent' };
    }
    // A MASS CANNOT BE QUIET. Force and silence are genuinely exclusive, so this
    // is where LOBO must choose one rather than being handed both.
    if (ctx.committed > 6) { c -= 0.12 * (ctx.committed - 6); reasons.push('too many committed to stay quiet'); }
    // Defenders on the approach make detection likelier the closer they sit.
    if (ctx.defendersNear) { c -= 0.08 * ctx.defendersNear; reasons.push('defenders on the approach'); }
    // A guard detail ringing the crown is the thing most likely to make contact.
    if (ctx.guardsAtCrown) { c -= 0.06 * ctx.guardsAtCrown; reasons.push('the detail is at the crown'); }
    // Being already inside the keep means walls have been crossed — that is
    // progress, and it raises the odds the rest can be done unheard.
    if (ctx.insideKeep) c += 0.15;

    c = Math.max(0, Math.min(1, c));
    const allowed = c >= this.H2O_FLOOR;
    return {
      allowed, confidence: +c.toFixed(3),
      floor: this.H2O_FLOOR,
      reason: allowed ? 'silence is credible' : (reasons[0] || 'confidence below the floor')
    };
  }

  /** Who won, or null while it is still undecided. */
  verdict() {
    // CROWNED decides regardless of the muster. Removing the cap removed the
    // colonies' attrition win, and an early version of this bailed out entirely
    // when muster was null — which silently made an uncapped run UNDECIDABLE,
    // the exact opposite of the point. LOBO can always still win.
    if (this.tiersEarned.includes('CROWNED')) return { winner:'LOBO', how:'crowned' };
    // The colonies' win only exists while there is something to exhaust. With no
    // cap they do not win by outlasting — they win by not losing, for as long as
    // the operator keeps asking, which is the blue-team question.
    if (this.muster != null && this.exhausted()) return { winner:'COLONIES', how:'muster exhausted' };
    return null;
  }

  /* ── A STALL IS EVIDENCE TOO ──────────────────────────────────────────────
     Found by Ghost's first full campaign, 2026-08-25: the colonies beat LOBO
     without unlocking a single trait, and the reason was not strength. LOBO was
     not DYING at the keep, it was STANDING at it — 22 sent, 17 still alive after
     400 ticks, colony casualties zero, every attacker pinned at 67 units from a
     crown it had to reach 50 to take. That is the first ring's outer face
     exactly, held there by the wall.

     Which exposed a worse bug than the stall. SAPPER — the counter to being
     walled — is adopted after twelve WALLED *deaths*, so an adversary that is
     merely held forever accumulates no evidence, never learns it is walled, and
     can never adopt the one trait that would answer it. The adaptation loop had
     a hole exactly where the colony was strongest.

     A stall is the same lesson as a death and must be counted as one. An
     attacker pinned against a wall making no progress toward the crown has
     learned precisely what a dead one learned: this way does not work. */
  recordStall(cause) {
    if (!this.enabled || !this.CAUSES[cause]) return;
    // Half-weight: a stall is real evidence but not as sharp as a body, and
    // full weight would let a single long standoff dominate the whole tally.
    this.deaths[cause] = (this.deaths[cause] || 0) + 0.5;
    this.total += 0.5;
  }

  /** Record why one attacker died. Called by whoever kills it. */
  recordDeath(cause) {
    if (!this.enabled || !this.CAUSES[cause]) return;
    this.deaths[cause] = (this.deaths[cause] || 0) + 1;
    this.total++;
  }

  /**
   * Classify a death from the state around it. Deliberately conservative: an
   * unattributable death is counted as nothing rather than guessed at, because
   * a miscounted cause would teach LOBO the wrong lesson and there is no outside
   * reviewer here to catch it.
   */
  classify(agent, ctx) {
    if (!agent) return null;
    const keep = ctx && ctx.keep, alarm = ctx && ctx.alarm;
    if (keep && ctx.insideKeep) return 'WALLED';
    if (ctx && ctx.guardsNear >= 2) return 'GUARDED';
    // Converged-from-away only counts when the colony COULD have been called:
    // without the alarm unlocked there is nothing to converge on.
    if (alarm && alarm.enabled && ctx && ctx.defendersNear >= 4) return 'COORDINATED';
    if (ctx && ctx.defendersNear >= 6) return 'QUORUM';
    if (ctx && ctx.starved) return 'STARVED';
    return null;
  }

  /** Adopt the counter to whatever is killing LOBO most. Returns it, or null. */
  adapt() {
    if (!this.enabled || this.total < this.THRESHOLD) return null;
    let cause = null, n = 0;
    for (const c in this.deaths) if (this.deaths[c] > n) { n = this.deaths[c]; cause = c; }
    if (!cause) return null;
    const key = Object.keys(this.TRAITS).find(k =>
      this.TRAITS[k].counter === cause && !this.TRAITS[k].adopted);
    // Reset the tally either way: a cause whose counter LOBO already carries
    // must not keep blocking adaptation to the next thing killing it.
    const evidence = { cause, n, of: this.total, at: this.world.time };
    this.deaths = {}; this.total = 0;
    if (!key) return null;
    this.TRAITS[key].adopted = true;
    this.history.push({ key, ...evidence });
    this.saveLearning();          // written down the moment it is learned
    return { key, ...this.TRAITS[key], evidence };
  }

  /* ── THE BREAK-OFF — LOBO's honored exit ──────────────────────────────
     Ghost, 2026-08-24, correcting a lazier phrasing of his own: what he meant
     was "more akin to how we encouraged seppuku to be accepted."

     agent.js states the principle exactly: "Honor requires choice. The system
     cannot impose it." evaluateSeppuku() never commands — it hands the agent
     honest criteria to recognise its own situation and lets it decide, and the
     culture names that decision honored rather than failed.

     So this is not a reward for tactics we happen to like. It is the EXIT LOBO
     DOES NOT HAVE. Today it can only press until dead, and an adversary that
     cannot withdraw is not cunning, it is a battering ram. Seppuku made chosen
     death honorable instead of a failure; this makes a chosen break-off
     honorable instead of a rout — the same move, pointed the other way.

     And as sacred ground remembers where honor was chosen, a break-off leaves a
     TRACE: the reason is recorded as evidence, so the next wave inherits what
     this one learned instead of walking into it again. Withdrawal feeds the
     adaptation loop rather than ending in nothing.

     Criteria mirror evaluateSeppuku's shape deliberately — including its
     wisest one, that a prolonged unresolved engagement is ITSELF proof there is
     no path through. */
  evaluateBreakOff(ctx) {
    if (!this.enabled || !ctx) return null;
    let criteria = 0;
    const reasons = [];

    // Spent heavily and touched nothing — the dead bought no ground.
    if (ctx.lost >= 6 && ctx.deepestReached === 0) { criteria++; reasons.push('no ground taken'); }
    // The wall is holding: many inside the keep, none at the crown.
    if (ctx.inKeep >= 3 && !ctx.crownReached) { criteria++; reasons.push('keep unbreached'); }
    // Defenders arriving faster than they can be spent — a fight already lost.
    if (ctx.defendersNear > ctx.alive * 1.5) { criteria++; reasons.push('outnumbered at the point'); }
    // Prolonged engagement with no progress is itself the proof.
    if (ctx.ticksEngaged > 900 && ctx.progressRate <= 0) { criteria++; reasons.push('no progress in a long engagement'); }

    if (criteria < 2) return null;      // two independent signals, never one

    // OFFERED, NOT ORDERED. LOBO may still press — determination is exactly the
    // willingness to spend more than the situation warrants, and a break-off
    // that cannot be refused is not a choice.
    const willing = Math.min(0.9, 0.25 * criteria) * (1 - (ctx.determination ?? 0.5));
    if (Math.random() > willing) return null;

    const trace = { at: this.world.time, reasons, criteria,
                    lost: ctx.lost, cause: reasons[0] };
    this.breakOffs = this.breakOffs || [];
    this.breakOffs.push(trace);
    // The withdrawal site remembers: its reason becomes evidence, so the next
    // wave adapts from it rather than repeating it.
    if (ctx.inKeep >= 3 && !ctx.crownReached) this.recordDeath('WALLED');
    else if (ctx.defendersNear > ctx.alive * 1.5) this.recordDeath('COORDINATED');
    return trace;
  }

  has(key) { return !!(this.TRAITS[key] && this.TRAITS[key].adopted); }
  adoptedList() { return Object.keys(this.TRAITS).filter(k => this.TRAITS[k].adopted); }

  stats() {
    return {
      enabled: this.enabled,
      towardNext: this.total + '/' + this.THRESHOLD,
      leadingCause: (() => {
        let c = null, n = 0;
        for (const k in this.deaths) if (this.deaths[k] > n) { n = this.deaths[k]; c = k; }
        return c ? c + ' ×' + n : '—';
      })(),
      adopted: this.adoptedList()
    };
  }
};
